// Hostaway amenity names are English and overlapping (Internet / Wireless /
// Free WiFi). We show only the ones a guest actually decides on, in Portuguese,
// collapsing synonyms; anything not listed here is left out on purpose.
const PT: Record<string, string> = {
  Internet: "Wi-Fi",
  Wireless: "Wi-Fi",
  "Free WiFi": "Wi-Fi",
  Kitchen: "Cozinha completa",
  "Cooking basics": "Utensílios de cozinha",
  Microwave: "Micro-ondas",
  Oven: "Forno",
  Refrigerator: "Geladeira",
  Dishwasher: "Lava-louças",
  "Coffee/tea maker": "Cafeteira",
  "Electric kettle": "Chaleira elétrica",
  TV: "TV",
  "Air conditioning": "Ar-condicionado",
  Heating: "Aquecimento",
  "Ceiling fan": "Ventilador de teto",
  "Laptop Friendly workspace": "Espaço de trabalho",
  Office: "Escritório",
  "Washing Machine": "Máquina de lavar",
  Dryer: "Secadora",
  Iron: "Ferro de passar",
  "Hair Dryer": "Secador de cabelo",
  Linens: "Roupa de cama",
  Essentials: "Itens básicos (toalhas, sabonete, papel higiênico)",
  "Hot water": "Água quente",
  "Room darkening shades": "Cortinas blackout",
  Elevator: "Elevador",
  Doorman: "Portaria",
  "24-hour checkin": "Check-in 24h",
  "Private entrance": "Entrada privativa",
  Balcony: "Varanda",
  "Garden or backyard": "Jardim ou quintal",
  "Outdoor grill": "Churrasqueira",
  "Outdoor furniture": "Móveis externos",
  Hammock: "Rede",
  "Swimming pool": "Piscina",
  Jacuzzi: "Jacuzzi",
  Sauna: "Sauna",
  "Communal sauna": "Sauna no condomínio",
  Gym: "Academia",
  "Fitness center": "Academia",
  "Exercise equipment": "Equipamentos de ginástica",
  "Free parking": "Estacionamento gratuito",
  Garage: "Garagem",
  "Electric vehicle charger": "Carregador para carro elétrico",
  "City view": "Vista da cidade",
  "Beach view": "Vista para o mar",
  "Beach front": "Pé na areia",
  Beach: "Perto da praia",
  "Beach essentials": "Itens de praia",
  Breakfast: "Café da manhã",
  "Suitable for children": "Ideal para crianças",
  "Suitable for infants": "Ideal para bebês",
  "Baby crib": "Berço",
  "Pack n play travel crib": "Berço portátil",
  "Long term stays allowed": "Estadias longas",
  "Smoke detector": "Detector de fumaça",
  "Fire Extinguisher": "Extintor de incêndio",
};

export function translateAmenity(name: string): string | null {
  return PT[name] ?? null;
}
